spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdooldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

file:
  upload-dir: "/Users/hyunpark/Desktop/B-Dool-Server/uploaded/"
